### ISSUE TITLE
[Bug] Various quitting and joining bugs with modded servers

### ISSUE THREAD

**Issue by snepsnepsnep** [BeamMP/BeamMP#166]
The Quit button on the BeamMP top menu very often doesn't quit to the main menu, just does a long freeze (likely unloading mods) and the game stays loaded in the map.

Using the BeamNG left side-bar quit button works immediately, but you have to Esc to escape the 'phantom' loading screen, after that any further joining is broken (loading screen doesn't appear after the mods have been loaded, just stays locked while loading the map, and eventually after the map is loaded you end up not being a multiplayer session).

If lua is manually reloaded upon reaching the main menu, further joins work as expected.

![image](https://user-images.githubusercontent.com/11176350/141314824-041696ea-736f-4c7e-8a13-95c4cc287efa.png)
(what the game looks while loading into a map without the loading screen)
End result after that is no UI modules are present, and pressing Esc to open the side-bar UI menu brings up the menu with the server list and the rest of things.

Using the BeamMP UI app Quit button will also sometimes just bring up the phantom loading screen, which has to be escaped with ESC, and the multiplayer ui modules might still be loaded this time so pressing the quit button again actually brings to the main menu.

Also seems like the more quits and rejoins are done without lua reloads, the more intense the chat duplication bug gets.
![image](https://user-images.githubusercontent.com/11176350/141316653-bdd5dd5e-9c72-480c-94a5-240341f13588.png)

Most of this is very inconsistent.

**Comment by Starystars67** [comment]
Thank you for doing some research into this for us @snepsnepsnep We can at least take this and dissect the code further to find the causes of these issues and produce fixes for them.

**Comment by 20dka** [comment]
ive spent quite a bit trying to figure out a solution to this issue. firstly i moved a portion of the code that causes these issues to a more appropriate place and then came to the conclusion that the only current solution is to delay the GE lua reload until we are in the main screen, past any loading areas. i am still working on a reliable solution

**Comment by JamminR** [comment]
Perhaps a new bug is necessary, feel free to split or tell me to split into a new bug.
Since NG .24.01 + BeamMP 4.(?) - The Quit button does NOT take us back to the main menu at all.
NG acts as though still running game. (think can still drive around, just no other players/not truly connected)
In addition, and worse, and likely a new bug, once you hit ESC, go to main menu, select multiplayer, select a new server, for a split second it acts as though it will connect, then, you go back to the server list again. Hitting ESC clears the server list and places your GUI back at the point you hit quit from the previous server (unless you'd driven around aka freestyle)

**Comment by lionkor** [comment]
I recommend this issue be split up into actual separate bug reports
