### ISSUE TITLE
Server source code & linux support

### ISSUE THREAD

**Issue by davtur19** [BeamMP/BeamMP#19]
The repo link does not exist and leads to a page with an error 404
https://github.com/Starystars67/BeamNG-MP#servers
(https://github.com/Starystars67/BeamNG-MP-Server/)

The wiki is offline with an error 502
https://wiki.beamng-mp.com/en/home/Server_Mod

Seriously make the server open source, it doesn't make sense that you have to pay to host a server to play with friends, I don't want to use servers with 200ms of ping .-.
In all the servers I try to connect to it tells me "full or outaded server". 
The mod is unusable without decent servers.

It would be useful to have an installer for Linux too, instead of running an .exe
And why should the laucher connect to discord?

EDIT:
I was able to understand that in order to join the servers I had to log into your discord server, although the error was not clear
I don't think it's smart to rely on discord to join a server as it is often offline

**Comment by 20dka** [comment]
The github repo might be for the old version (which ran on js iirc?)
Discord is used as a simple way of authentication, as for the wiki, I think it's down for maintenance.

**Comment by Starystars67** [comment]
Hello, Sorry about the issue you are finding there regarding the link to the repository. We have taken down the public version of the server code due to the full rewrite we did in a different language and the shear amount of people who kept downloading this version but then complaining about the fact it was not working.

The wiki is back online sorry for the downtime there I did some large scale maintenance on the server it was hosted on and had some issues getting the wiki back online but it is now.

Regarding the open sourceness of the server software, we have chosen to keep the core system private due to some efforts that were made to take our work and then sell it off as their own.

As for the issue you are encountering around "full or outdated server" please make a ticket in our discord and I am sure we can figure this out for you.

The reason we have not done any active effort into linux eg an installer for it is because the game does not support it. It would not be in our interest to support something that the game does not support. Regarding the use of Discord we felt this was the best way for a method of authentication and to be able to hold those who want to be rude and disrespectful accountable.

Finally regarding your comment about it not being clear on the error. We are doing lots of work behind the scene at the moment on making all of the project clearer and easier to use.

**Comment by davtur19** [comment]
I opened the issue because it wasn't clear that this repo was old, then looking better online I realized it was an old version; it would be useful to write it in the readme.

There have always been script kiddies as long as there are stupid people buying it, I don't see why this should be a problem, making it open source would help development.

The "full or outdated server" problem has already been solved by logging into your discord, it was an unclear error, I didn't have an old version, I just didn't authenticate with discord. I only realized this after looking for an online guide (the wiki was offline).

The linux version works perfectly without using wine or other programs, just enable Steam play from the Steam settings and press play.

Regarding discord authentication it seems to me a very bad method to force people to install discord when it can only be used from browsers, you could just use Steam as authentication (like fivem) or just ban people for ip ...
If you know how to manage a server, you will already know how to ban VPNs, proxies, TOR, etc ...

However the UI doesn't work at all, you can't sort servers by name, ping or player, but I think you already know that.
Also, I and a friend have wasted a lot of time understanding that the direct connection to the server doesn't work if you put a domain, with an error that didn't help to understand it...

**Comment by 20dka** [comment]
A UI overhaul is in the works as we speak that should address sorting issues among others

**Comment by TheHellBox** [comment]
@davtur19 I'm trying to build a new multiplayer mod for your specific reason. I'm running linux too and I don't really want to install discord on proton. Also I feel like multiplayer will benefit a lot from beeing open source, rather than private. I have some progress and working prototype, contact me on discord if you want to join testing: 
`The HellBox#3589`

**Comment by Anonymous-275** [comment]
fun fact i am already working on the server to be cross-platform i don't get the "I will make it myself revolution" when really we never said we will not do it :)

**Comment by Anonymous-275** [comment]
Server is now open source and does support linux.
