### ISSUE TITLE
[Bug] Mod loading freezes when tabbed out of the game

### ISSUE THREAD

**Issue by Mack29446** [BeamMP/BeamMP#190]
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
When downloading mods from a server on the server list, if you highlight another window and "tab out" of BeamNG, the file just downloaded will not complete the "Loading Resource" phase until BeamNG is highlighted again. This is very annoying for those with slower internet connections, who may want to do something else while waiting for mods to download.

**To Reproduce**
1. Join a server with >1 mod
2. Highlight another window while the first mod is downloading
3. The "connecting" box will get stuck on "Loading Resource"

**Expected behavior**
The mods should load irrespective of whether the BeamNG game window is highlighted or not.

**Screenshots**
![GIF of issue](https://user-images.githubusercontent.com/41524393/148107255-9eaef65f-e033-4c18-9f48-2b67c439bf97.gif)

**Desktop**
Windows 11 x64 Build 21H2

**Comment by 20dka** [comment]
Hey, this seems to be a BeamNG related issue, as they stop reporting file system changes when the window goes out of focus. In the options there is an Alternative mod loading setting which is a workaround for this bug.

**Comment by JamminR** [comment]
FYI - I've tried the alternate loading checkbox in MP options - though the mods do indeed seem to keep loading when BeamNG isn't focused now, in my experience, it seems to hang at the final mod and never loads the map/spawn. Just sticks at loading screen whether it was focused or not.
Might be worthy a new bug report if anyone can reproduce it besides me, since technically, this OP report is for a different issue.
