### ISSUE TITLE
[Bug] Client Redownloads mods from server every time and wipes out the /mods/multiplayer folder

### ISSUE THREAD

**Issue by synth80s** [BeamMP/BeamMP#85]
Client does not verify mods installed but rather downloads them from the server every time. I can see the mods/multiplayer folder being erased, then each mod zip being individually transferred to it from the server.

**Comment by Olrosse** [comment]
How it works is that it downloads mods to the resources folder in the location where the launcher is installed, then it copies them into the mods folder on join, if it says loading resources when you join then it means the mods have already been downloaded

**Comment by Starystars67** [comment]
Can we confirm if this is a bug found in this particular case or just a miss understanding please?

**Comment by jojos38** [comment]
The multiplayer mod being erased is meant to happen, the mods are stored in the launcher folder
However they shouldn't be redownloaded everytime

**Comment by synth80s** [comment]
Hi guys thanks for responding. It could certainly be a misunderstanding but I haven’t been able to look at the code yet (been dealing with some server issues). I just want to lend a hand if possible (sw engineering background). 

It seems like the mods are loaded into the appdata location, then copied over to the mods folder. I have to verify this first. When loading into a server, the mod verification process is rather slow even on my own local network. If the mods are indeed only being copied from app data to the mods/multiplayer directory, this seems like a lot of overhead and excesses ware on the drive. I also see the mods are removed upon exit, if I close out of the game they start there and single player complains about duplicate mods. When executing the launcher if it counts more than 3 mods it wipes out the entire mods/multiplayer folder.

Why can’t the multiplayer client just point to the mods folder? Sure the server won’t have everything but it can simply compare the names of the zips to whats in the resources folder on the server. If they match, they are verified, if not, download any additional mods into that folder.

**Comment by Starystars67** [comment]
Hi @synth80s It is nice to see some community interaction with the mod on more than a playing level!

We download the mods (and compare them with the server from) the resources folder in the launcher which is likely located in your appdata folder. We do this because the mods are removed from the game when you leave as you pointed out, we did this because otherwise you end up with 100's of mods in your game when you might only be using 1 or two. This is why we remove them each time as it helps to keep the game running faster.

The reason it takes a long time for the mods to properly load even when they are copied from disk is because the game is _VERY_ slow at loading them. We originally just copied them all into the game however we found that it often did not load half of them so we had to change to a system where when the game has loaded a mod it then tells the launcher to give it then next mod. This process continues until they are all loaded. We agree this is by no means the best solution but it was the only reliable system we could get working with the game correctly at the time.

If you have any suggestions we would be happy to hear you out!
It is all a bit of fun and research at the end of the day :)

**Comment by synth80s** [comment]
> Hi @synth80s It is nice to see some community interaction with the mod on more than a playing level!
> 
> We download the mods (and compare them with the server from) the resources folder in the launcher which is likely located in your appdata folder. We do this because the mods are removed from the game when you leave as you pointed out, we did this because otherwise you end up with 100's of mods in your game when you might only be using 1 or two. This is why we remove them each time as it helps to keep the game running faster.
> 
> The reason it takes a long time for the mods to properly load even when they are copied from disk is because the game is _VERY_ slow at loading them. We originally just copied them all into the game however we found that it often did not load half of them so we had to change to a system where when the game has loaded a mod it then tells the launcher to give it then next mod. This process continues until they are all loaded. We agree this is by no means the best solution but it was the only reliable system we could get working with the game correctly at the time.
> 
> If you have any suggestions we would be happy to hear you out!
> It is all a bit of fun and research at the end of the day :)

Thanks for the reply! Absolutely, I appreciate the work you guys have done, made lots of users happy to finally have a multiplayer to engage with others. My buddy and I really enjoy it, I host my own server in debian.

I understand the implications and see why that is the case. So from my understanding you negotiate the copy one mod at a time instead of doing a batch copy? That would certainly increase execution time of that "algorithm". I would like to sit on this for a while and think about. 

In the meantime, could a compromise be implemented? For example, compare the mods from the server against the client mods in the beamng/mods directory. If they are there, all is good. For any additional mods, download to appdata and transfer over to the game upon load. This would significantly reduce overhead as the mods that I already contain for my single player are also on my server. For those of us who are repeat customers to servers (my friend and I have all the same mods), we should expect to see improved runtime. This would allow the single player folder to not bloat, while still giving you the flexibility to download mods from other servers. Let me know your thoughts. 

Thanks!

**Comment by Starystars67** [comment]
> Thanks for the reply! Absolutely, I appreciate the work you guys have done, made lots of users happy to finally have a multiplayer to engage with others. My buddy and I really enjoy it, I host my own server in debian.

Glad to hear buddy!!

> I understand the implications and see why that is the case. So from my understanding you negotiate the copy one mod at a time instead of doing a batch copy? That would certainly increase execution time of that "algorithm". I would like to sit on this for a while and think about.

Correct, We tried to batch move into the game however its mod loading system wouldn't pick them all up unfortunately.

> In the meantime, could a compromise be implemented? For example, compare the mods from the server against the client mods in the beamng/mods directory. If they are there, all is good. For any additional mods, download to appdata and transfer over to the game upon load. This would significantly reduce overhead as the mods that I already contain for my single player are also on my server. For those of us who are repeat customers to servers (my friend and I have all the same mods), we should expect to see improved runtime. This would allow the single player folder to not bloat, while still giving you the flexibility to download mods from other servers. Let me know your thoughts.

We do compare between launcher and server as the launcher keeps a copy of the mods so you do not have to download them again. The mod are deleted when the session ends because it helps to reduce the issue of them persisting between sessions. I do agree this has a downside in that if you join the same server again you have to load them again. We are currently experimenting with a new Lua system which maybe we can also add a new mod loading system into this too? We will have to see.

**Comment by synth80s** [comment]
> We do compare between launcher and server as the launcher keeps a copy of the mods so you do not have to download them again. The mod are deleted when the session ends because it helps to reduce the issue of them persisting between sessions. I do agree this has a downside in that if you join the same server again you have to load them again. We are currently experimenting with a new Lua system which maybe we can also add a new mod loading system into this too? We will have to see.

I don't think I explained it well enough. Hopefully this isn't too confusing but these are my observations and suggested solution below.

1.   Client connects to server
   a.   Do you have necessary mods?
      i. No 
         1.   Copy from server to appdata directory
         2.   Copy from appdata into Documents/beamng/mods/multiplayer
         3.   Load one at a time into game
      ii.Yes
         1.   Copy from appdata to Documents/beamng/mods/multiplayer
         2.   Load one at a time into game
         2.   Exit session
         3.   Delete mods from Documents/beamng/mods/multiplayer

Proposed solution:
1.   Client connects to server
   a.   Do you have necessary mods?
      i.   Are any of these mods installed for single player? (Documents/beamng/mods/repo)
         1. Yes
            a.   Load mods directly from repo location (single player)
      ii.   Are there any additional mods not installed from single player that need to be transferred from the server?
         1. Yes
            a.   Copy from server to appdata directory
            b.   Copy from appdata into Documents/beamng/mods/multiplayer
            c.   Load one at a time into game
         2. No
            a.   Load game
2.   Exit session
3.   Delete mods from Documents/beamng/mods/multiplayer

This solution should decrease load times if a large amount of mods are already installed into single player Documents/beamng/mods/repo. 
For instance, if I have the same mods in my single player as I do on my server, the game should load them as normal upon boot. 
Then when connecting to my multiplayer server, it should start loading the map immediately.

**Comment by Starystars67** [comment]
I see what you are saying a bit better now. 
We can try to do something on these lines yes but I have a feeling there was a reason why we did not do this originally. I do not remember why now but we can look into it again either way!

**Comment by antoniogermano** [comment]
Hello everyone!

Well first I'd like to say I'm very happy about BeamMP, I just found out about it recently and I already love it. BeamNG is pretty awesome online and we have you to thank for this. I would like to help you if I can (like synth80s, I also have a software engineering background).

I have thought about a quick/dirty workaround for this issue... it goes like this:

1. Save the server the user wants to connect to a file.
2. If the server has, say, more than 5 mods, close the game.
3. Copy all of the mods at once (that should be fast).
4. Open the game again.
5. When the game finishes loading the main menu, automatically connect to the server saved on file without loading any mods,  because I think we can assume when BeamNG opens, it already has all the mods correctly loaded.
6. Delete the file (so that when the game launches again, it doesn't connect to that server again).

Do you think this could work? I think copying all of the mods then restarting the game is definitely faster than loading 115 mods. I tested a server with this amount of mods and it takes over 30 minutes to join. If joining fails, you even have to load all of them again on the next try...

> We are currently experimenting with a new Lua system which maybe we can also add a new mod loading system into this too? We will have to see.

Do you have a planned date for the release of the new Lua system? Are you doing it to make the mods load better from source? Can we help with it somehow?

**Comment by Starystars67** [comment]
Hello @antoniogermano thank you for the input towards the matter!! It is nice to see community engagement starting to grow!

Interesting concept you have there. Theoretically this could work yes however I would question the time it will take for some in closing the game, moving the mods and then starting the game back up. The starting back up would be the part that would take 
the longest in my opinion. 

I know from experience that it can take a hot moment sometimes.

One idea we had been thinking about was if we were to find a way to somehow inject a list of mods rather than waiting for the game to "detect" their presence. This way we can tell the game to load all of them as soon as the launcher was done copying them into the user directory. @lionkor @Anonymous-275 thoughts?

I know that @jojos38 is currently doing a rewrite of the network code for within the game with @Anonymous-275 help for the launcher so that we can introduce reconnecting on connection loss and reattempting download of resources should it fail. Also this will hopefully allow for mod loading on the fly during the game session too. 
Hopefully this will help to some degree.

I hope this helps?

**Comment by legraphista** [comment]
Copying stuff is slow, could symlinks work?

There could be a folder with all the mods ever downloaded, with the file name as a hash of their contents (sha-256 will have no collision) to prevent conflicts & deduplicate, and a server would send the list of hashes it requires.  
If the hash is present in the files of the download folder, you could symlink them to the mods folder, otherwise download them & symlink them.  
Once disconnected, you could clear the folder of symlinks, ready for the next server connection.

On linux symlinks or hardlinks would work wonders, but I'm not sure on windows if it will behave as expected

**Comment by 20dka** [comment]
my experience with symlinks on windows hasnt been great, but we could give it a try. hash file names is an idea i suggested a while ago, so im all for it

**Comment by Anonymous-275** [comment]
symlinks was originally on my ideas list since i agree with you copying files over isn't the best thing. It's just that the way we currently load mods rely on the game picking up a new mod that was put inside the mods folder so we just need to test if it would work.

**Comment by legraphista** [comment]
Can you make hard links in windows? They're indistinguishable from a file copy unless you specifically look for it.

**Comment by Anonymous-275** [comment]
> Can you make hard links in windows? They're indistinguishable from a file copy unless you specifically look for it.

yes of course C++ has a standard way of doing such a thing, but i think in our case we want a soft link :). I added the card on our trello for me to remember it in future launcher updates.

**Comment by Starystars67** [comment]
On this matter, some further revision and digging into this has been done by @jojos38 and it looks like we might be able to do bulk mod loading in the game finally!!!

**Comment by trevevs** [comment]
> On this matter, some further revision and digging into this has been done by @jojos38 and it looks like we might be able to do bulk mod loading in the game finally!!!

Bulk loading?? what do you mean?  Is this a manual hack?  seems to behave in the same way atm.  Deletes mod folder on start.  Really dont understand the reasoning behind this. Don't see why it cant scan the existing mods folder and use that.  its pretty much unusable for servers that require a few mods to be downloaded, just takes too long.

**Comment by Starystars67** [comment]
Hi @trevevs sorry for the massively delayed response here.

Firstly the crash that you seem to be getting please open an issue over on the [Launcher](https://github.com/BeamMP/BeamMP-Launcher) repository.

As for the mod downloading / loading this is still being investigated however it is just taking us more time that we would like as it has opened a whole rats nest of things to look into and dissect.

We are still working to find a way to do the bulk mod loading or at minimum load them more efficiently.

**Comment by Starystars67** [comment]
Issue seems to be resolved now. Unsure why this was not updated.
